### ISSUE TITLE
Add Customizable Grid for Alignment and Guiding Purposes

### ISSUE THREAD

**Issue by RednibCoding** [PintaProject/Pinta#1028]
**Description**
Currently, the image editor lacks a grid feature for guiding and aligning elements. I’d like to request the addition of a customizable grid that users can toggle on and off. This grid should allow users to adjust the width and height of the grid cells, providing flexibility for aligning elements precisely. A grid is a common feature in most image editors, and not having one makes precise alignment more difficult.

**Additional context**
![image](https://github.com/user-attachments/assets/adf135d0-bca4-423e-a39a-b789da3884a1)
![image](https://github.com/user-attachments/assets/3f5c2cac-8d23-4b5c-97bf-239bdf78d93b)

**Comment by cameronwhite** [comment]
The canvas widget can show a pixel grid currently, so I think the approach would be to extend that to be more customizable

**Comment by cameronwhite** [comment]
Fixed by #1105
