### ISSUE TITLE
old GUI

### ISSUE THREAD

**Issue by temginson** [PintaProject/Pinta#1041]
**Description**
is there an option to get back the old GUI

**Additional context**
i prefer the old GUI in some places

**Comment by cameronwhite** [comment]
Can you provide more information about the issues? e.g. specific things that have changed which don't work as well for you

**Comment by temginson** [comment]
its just that in color picker i liked to be able to press down the color slider and have a nr that i could ajust the colors

**Comment by cameronwhite** [comment]
Thanks, I think this can be merged into bug #570 then. There is some in-progress work on implementing an improved color picker dialog
