### ISSUE TITLE
Brush stroke not being undone correctly

### ISSUE THREAD

**Issue by Lehonti** [PintaProject/Pinta#1072]
**To Reproduce**
- Open a blank document
- Set the primary color to something that contrasts with the background
- Select the 'paintbrush' tool and set the brush width to something considerable like 20
- Paint any stroke, and then undo the action
- A part of the stroke will be deleted, and part of it will remain. It is not just a visual leftover, but it is actually drawn on the canvas, as you will see if you apply effects to it

**Additional Info**
- Different shapes of strokes leave different marks, so when reproducing the bug, you could try drawing different shapes, like lines at different angles, a V, circles or other twisted shapes, etc., or you could draw them backwards, or experiment with strokes that start and end at different positions etc.
- This doesn't happen in Pinta 2.1.2, so it most likely is caused by recent changes.

**Version**
Running it on Windows 11. The windows build artifact of this pull request was used: https://github.com/PintaProject/Pinta/pull/1051 but surely it comes from a different change

![image](https://github.com/user-attachments/assets/4e884c42-4738-45b1-aa84-b79474309028)

![image](https://github.com/user-attachments/assets/4b71665a-c039-45b1-9760-3f5264850a2f)

My guess is that the bounding rectangle for the undo action is not being calculated correctly, but I might be wrong about that.

**Comment by cameronwhite** [comment]
I ran `git bisect` which indicates this was introduced by 8c087af44d45ccb5e14f9d8a0c4fd1588e850e0b
