### ISSUE TITLE
[Question] Delete old projects to restore

### ISSUE THREAD

**Issue by zwillikon** [PintaProject/Pinta#1074]
When I build Pinta
`/usr/bin/dotnet publish Pinta.sln --configuration Release -p:BuildTranslations=true -maxcpucount:1 --self-contained false -p:PublishDir=./pinta/src/Pinta/publish`

my .NET SDK wants to restore an old private project of mine:

```
  Determining projects to restore...
.Pinta/installer/addins/Pinta.AddinUtils.csproj : error NU1301: The local source '[old_private_project]/csharp' doesn't exist. [./pinta/src/Pinta/Pinta.sln]
```

This is obviously out of your domain – I would be nevertheless glad for an answer. How do I direct _dotnet_ to give up on and delete those old builds?

**Comment by cameronwhite** [comment]
There is probably some nuget configuration somewhere that's referring to those old folders - I assume at some point they were added as extra package sources

You could look for a `nuget.config` file under the `~/.nuget` folder and see if you can edit out those old references. Or, `dotnet new nugetconfig` would generate you a fresh default configuration file

**Comment by zwillikon** [comment]
I've never used nuget.

**Comment by cameronwhite** [comment]
I'm not really sure what else to suggest, other than just wiping your `~/.nuget` folder entirely?

It looks like `dotnet new nugetconfig` just generates a new `nuget.config` file in your current directory, so you'd have to move that to replace the one under your ~/.nuget folder

**Comment by zwillikon** [comment]
@cameronwhite I don't have nuget (or pip, conda, conan, ...) installed.

**Comment by cameronwhite** [comment]
Sorry yeah, I should have clarified that dotnet is using nuget internally for packages
