### ISSUE TITLE
Palatte color changes interacts with text tool in unexpected ways

### ISSUE THREAD

**Issue by TheodorLasse** [PintaProject/Pinta#1097]
**Description**
When writing a text, but not finalizing it before selecting another tool and then changing primary color does not change the color of the text until the new tool is used, then the text is finalized with the new color. 

**To Reproduce**
Write text without finalizing, select other tool, change primary color, use new tool.

**Additional Info**
I've been seeing strange behaviour regarding text finalizing overall. Sometimes the text does not finalize properly leaving a piece of text that cannot be interacted with until a new text is written forcing the old one to finalize, but have not been able to reproduce this consistently. Most of this behaviour seems to happen when switching tool without finalizing the text first. Perhaps the best solution is to finalize text on tool switches?

**Version**
Windows 10, Master branch Pinta (version 2.1.2?)

**Comment by cameronwhite** [comment]
> Perhaps the best solution is to finalize text on tool switches

I think the intended behaviour is that text should only be finalized when you try to make some change to the text layer. E.g. you should be able to type some text on a layer, switch to another layer and modify it with some other tool, and then go back and re-edit the text on the original layer

So really the bug here is that finalizing the text is using whatever the current palette colour happens to be, rather than remembering which colour the text should be using

**Comment by TheodorLasse** [comment]
I think there's another bug then, if I'm understanding you correctly. Text objects are usually automatically finalized when using another tool. The only exception to this I have found is when the text tool is pre-selected on startup (I.E it was the tool last used before this startup). Using it then will not cause text to be finalized when using another tool. 

I could take a look at this and try to make the finalize behaviour a little more consistent

**Comment by cameronwhite** [comment]
Yeah, I agree that issue with starting up in the text tool sounds like a bug

I'd suggest trying to store the colors in the `TextEngine` alongside the font settings, so that they can be correctly finalized with their original colours instead of the current palette
