### ISSUE TITLE
Tool Windows don’t stay closed upon restart

### ISSUE THREAD

**Issue by lobre** [PintaProject/Pinta#1179]
**Description**
I would like "Layers" and "History" windows to stay closed when I restart Pinta to keep a minimalist interface without any bars of any kind. It works for everything under "View/Show|Hide" as they stay unticked upon restart. However, for "View/Tool Windows" that is not the case. If I untick them and restart Pinta, they appear enabled again. I know I can minimize them but then it is not as minimal as they stay as "tab buttons" on the right.

**To Reproduce**
Launch Pinta, go to "View/Tool Windows/" and disable "Layers" and "History". Now close Pinta and start it again. They are now enabled again. This would be nice if that choice persisted.

**Additional Info**
![image](https://github.com/user-attachments/assets/4fcfb532-e383-4f9e-853e-56cf924459a7)

**Version**
Ubuntu 22.04 with Pinta 2.1.2

**Comment by cameronwhite** [comment]
Confirmed in Pinta 2.1
In the master branch the behaviour has changed though so that the View -> Tool Windows menu items act the same as minimizing the pane rather than making them invisible. I think this happened in 9706906d569c7800f00b3684a7eb5c74338917d7 , so the issue now is whether that should be reverted, or a separate option is added to entirely hide the tool panel

**Comment by lobre** [comment]
> so the issue now is whether that should be reverted, or a separate option is added to entirely hide the tool panel

I don’t know exactly, but I think it could make sense to have something consistent between the "Show/Hide" and "Tool Windows" as their look similar with tickboxes.

![image](https://github.com/user-attachments/assets/84ecbe26-18e1-4532-a6fb-b79b3a32b7a5)

![image](https://github.com/user-attachments/assets/b8e694b7-1ade-4f9b-83f7-bd8f9207291c)

**Comment by cameronwhite** [comment]
One option would be to add a new entry under `Show/Hide`, which would completely hide the entire right panel.
I'm also not entirely sure if we still need the other `Tool Windows` menu with the toggles for the History and Layers pads, since those can be minimized and maximized through the UI

**Comment by lobre** [comment]
I agree. Those propositions would make sense. They seem to simplify, and that is a good thing. As of today (and from a fresh eye), I struggle to distinguish between minimizing versus hiding the panels completely. This solution would make that a bit more consistent.
