### ISSUE TITLE
Several Transparency Bugs for Effects

### ISSUE THREAD

**Issue by AshleyPikachu** [PintaProject/Pinta#1184]
**Description**
So for context, I've been making myself a guide for learning Gimp and Pinta as a Paint.Net user. Throughout all of that I have found several effects that have issues rendering their effects correctly when an used on an alpha channel.

**To Reproduce**
Just using the effects like normal.

**Effect List**
Ink Sketch
Fragment
Motion Blur
Radial Blur
Zoom Blur

**Version**
Rocky 9, Flatpak Pinta

Example
Fragment on a solid background - Working Correctly
![image](https://github.com/user-attachments/assets/87dd53c8-587e-4c12-a903-20c04d9378ee)

Fragment on an Alpha Channel - This glitched outline looks white in pinta, and looks even stranger here.
![image](https://github.com/user-attachments/assets/ffe14abf-6911-466a-aa9c-6da8bd4cc76b)

**Comment by cameronwhite** [comment]
Thanks for the report!

It looks like the fragment and motion blur effects happen to already have been fixed in the `master` branch by 29615a694a28802f05b9c698d3bae5bbaffd7df3

These ones still have issues with transparency:
- Ink Sketch
- Radial Blur
- Zoom Blur

**Comment by AshleyPikachu** [comment]
Awesome, how do I update?

**Comment by cameronwhite** [comment]
There are some installers automatically built from each commit at https://github.com/PintaProject/Pinta/actions

**Comment by AshleyPikachu** [comment]
Alright, I'm afraid im pretty new with this kind of update, I'm not sure what to do next after I load the page.

**Comment by cameronwhite** [comment]
Clicking on a particular build brings up a page like https://github.com/PintaProject/Pinta/actions/runs/12530029233, which has the available installers for testing.

**Comment by AshleyPikachu** [comment]
Thanks!
