### ISSUE TITLE
Very Large Fontsizes can't be changed back

### ISSUE THREAD

**Issue by oaklinq** [PintaProject/Pinta#1199]
**Description**
If you choose a very large font size (e.g. 600) and close the font window, after you reopen it, the font preview will be so big that the part where you can change the font-size back is off screen, and therefore can't be changed back.

**Additional Info**
![Bildschirmfoto vom 2024-12-30 15-42-28](https://github.com/user-attachments/assets/940f9735-701b-42a8-99f8-8b72ab00c7c8)

**Version**
Pinta 2.1.2 on Fedora 41 (Gnome 47.1)

**Comment by cameronwhite** [comment]
Thanks for the report! I could reproduce as well

This font dialog is a standard GTK dialog which is opened via [Gtk.FontButton](https://docs.gtk.org/gtk4/class.FontButton.html) so this isn't something we can fix in Pinta itself. I'd suggest submitting this to the GTK issue tracker: https://gitlab.gnome.org/GNOME/gtk/-/issues

**Comment by oaklinq** [comment]
Thanks, for the info. I will do that. 

I hope you'll have a fantastic new year!
