### ISSUE TITLE
Cannot reasonably draw a square at the edge of the image

### ISSUE THREAD

**Issue by stdedos** [PintaProject/Pinta#467]
**Description**

Starting from

![](https://github.com/PintaProject/Pinta/assets/133706/83c8c1e2-3c6e-41bd-9905-6b08654ccf03)

I am trying to remove the side-borders. Auto-crop doesn't work.

Trying to use the bucket, the black is not auto-painted (not all the blacks are of the same color)

I am then trying to draw center-wise to the edges white squares, and then use Auto-crop

![image](https://github.com/PintaProject/Pinta/assets/133706/10c71f33-f892-49f9-a640-b585310b2a88)

However, that seems impossible.

Filling the blacks with the bucket, instead, works.

**To Reproduce**
Steps to reproduce the issue.

**Additional Info**
If applicable, add a screenshot or attach an example file that demonstrates the issue.

**Version**

_Please create a Help -> Copy Template to fill that stuff_ 😕 

Ubuntu 20.04, flatpak, v2.1.1

**Comment by cameronwhite** [comment]
Confirmed, I think the easiest way to reproduce is to create a small 64x64 image and then try to draw a filled rectangle that covers the image. There's probably an off by one error that's causing the last row and column of the image to not be filled

For the original issue, I agree using the fill tool with a tolerance of around 25 works well.
