### ISSUE TITLE
Allow Touchpad gestures / Pinch to zoom

### ISSUE THREAD

**Issue by oaklinq** [PintaProject/Pinta#634]
**Description**
It would improve the workflow on laptops if you could zoom into the image by using pinch to zoom.

**Comment by cameronwhite** [comment]
👍 
This might be doable by adding https://docs.gtk.org/gtk4/class.GestureZoom.html to the canvas widget

**Comment by Matthieu-LAURENT39** [comment]
Really great feature, this made using pinta on laptops so much easier!
Thanks a lot!
