### ISSUE TITLE
 Feature request: Expand/Contract Selection

### ISSUE THREAD

**Issue by zWolfrost** [PintaProject/Pinta#661]
Hi, i'm using Pinta 2.1.1 on Ubuntu. I would really like an option to expand/contract your selection, like Photoshop does. Not to be confused with resizing your selection, which is already implemented. It would basically work like the attached screenshot. Thank you for this amazing program

![se_modify_border png img](https://github.com/PintaProject/Pinta/assets/101343066/04f81126-36c1-4f9b-9b72-38b3d7431201)

**Comment by cameronwhite** [comment]
Fixed by #746
