### ISSUE TITLE
When clicking on a layer to hide it, the layer should not be selected.

### ISSUE THREAD

**Issue by u5n** [PintaProject/Pinta#682]
**Description**
In pinta 2.1.1, when clicking on a layer to hide it, the layer will be selected.
![image](https://github.com/PintaProject/Pinta/assets/26353598/972a9b1d-6bdc-41ef-a29f-6666f627e4cf)
I hope that hiding the layer itself will not cause the layer to be selected.
**Additional context**
Ubuntu 22.04, snap install pinta
pinta version 2.1.1

**Comment by cameronwhite** [comment]
It looks like this is already fixed now in the `master` branch (upcoming Pinta 2.2 release). The layer list widget was rewritten when porting to GTK4 and that seems to have fixed the selection issue
