### ISSUE TITLE
Pinta 2.2-development, the screen unexpectedly move when zoom and use magic wand and change tolerance

### ISSUE THREAD

**Issue by u5n** [PintaProject/Pinta#698]
**Description**
The screen unexpectedly move when zoom and use magic wand and change tolerance.

**To Reproduce**
1. Open a image, zoom so that you can see vertical and horizontal scrollbars of the images.
2. Selec magic wand, select any area. 
3. Change tolerance to any other value.
4. Select any area again. This time you will see the screen move.

**Version**
Pinta 2.2-development version [Pinta-linux-dotnet-8.0.x.zip](https://github.com/PintaProject/Pinta/actions/runs/7523870398/artifacts/1168806389).
I use ubuntu 24.04 with gnome 45.

**Comment by cameronwhite** [comment]
Confirmed, it might be a more general issue with losing focus / moving the mouse outside of the canvas. I could reproduce something similar with the brush tool when adjusting the brush size in the toolbar on a zoomed-in image.
