### ISSUE TITLE
Pinta 2.2 - development - App crashed when trying to save file in ORA format

### ISSUE THREAD

**Issue by iksi4prs** [PintaProject/Pinta#712]
**Description**
App crashed when trying to save file in ORA format.

**To Reproduce**
Create new file, with some simple content (one layer is enough)
Save file, select ORA format.
App crash.

**Additional Info**
Error in line as shown in image (class GdkPixbufExtensions)
There is a label/tag there "TODO-GTK4" - is it still a "WIP" ?
![image](https://github.com/PintaProject/Pinta/assets/65832579/6fe8cc9d-8eeb-4acd-8f67-11222a6239a1)

**Version**
Checked on Windows 11, Pinta 2.2 (last build from master, last ( https://github.com/PintaProject/Pinta/actions/runs/7620666315 )

**Comment by cameronwhite** [comment]
Good catch, thank you for the report!
