### ISSUE TITLE
Touchpad/trackpad zoom is ridiculously, absurdly sensitive

### ISSUE THREAD

**Issue by NoSkillPureAndy** [PintaProject/Pinta#715]
**Description**
When holding ctrl and scrolling with a trackpad, it's impossible to control how much you zoom.

**To Reproduce**
1. Get a laptop
2. Open Pinta
3. Hold ctrl and scroll up and down with your trackpad

**Version**
Pinta 2.1.1, up-to-date EndeavourOS, KDE 5, X11

**Comment by cameronwhite** [comment]
Yeah, it scrolls very quickly when using a trackpad. I think the suggestion from #634 of supporting the standard zoom gestures is probably the correct solution for this, so I'll close this as a duplicate
