### ISSUE TITLE
dashed outline circle with large brush width

### ISSUE THREAD

**Issue by olsonpm** [PintaProject/Pinta#733]
**Description**
I'm expecting a solid outline when drawing a circle but it's dashed when increasing the brush width

**To Reproduce**
1. create new image, 100x100 works
2. draw a circle, set brush width to 10+, ensure the fill style is "fill and outline shape"
3. confirm the outline is dashed as in screenshot

**Additional Info**
![dashed-lines](https://github.com/PintaProject/Pinta/assets/5957709/e3a52aa6-4a30-4900-8bec-bcf17d021a4c)

**Version**
- latest arch linux as of writing
- pinta version 2.1.1

**Comment by cameronwhite** [comment]
Confirmed. I think the main thing to be investigated is whether this is from something Pinta is doing wrong on our end, or if it's an issue in the `cairo` drawing library
