### ISSUE TITLE
A color picker get incorrect color on the dimming picture

### ISSUE THREAD

**Issue by u5n** [PintaProject/Pinta#745]
**Description**
In "choose primary color", the color picker get incorrect color on the dimming picture

**To Reproduce**
1. Fulfill picture with "#00FF00"(green) color
2. Double Click to select primary color in the bottom left palette.
3. Under Custom click the "+" button
4. Now click "pick a color from the screen", try to pick green color from your picture, you will get the wrong  "#00B100"(dark green) color

**Version**
Ubuntu 24.04
Pinta "2.2+ba63d8807b2512911c7e5453312b317dddc4da84"

**Comment by cameronwhite** [comment]
Is this `Pick a color from the screen` option in the color chooser dialog? It must be a Linux-specific thing that GTK enables, since it isn't appearing for me on macOS. 

Using the `Color Picker` tool from Pinta's side toolbar is probably the better way to do this though, if you're wanting to pick a color from the image?

**Comment by u5n** [comment]
> Is this `Pick a color from the screen` option in the color chooser dialog? It must be a Linux-specific thing that GTK enables, since it isn't appearing for me on macOS.
> 
> Using the `Color Picker` tool from Pinta's side toolbar is probably the better way to do this though, if you're wanting to pick a color from the image?

![image](https://github.com/PintaProject/Pinta/assets/26353598/0a51a398-0dc2-4b9b-a7eb-4aef59e60e4e)

**Comment by cameronwhite** [comment]
Thanks, yeah I think that is something that GTK's color chooser dialog is only enabling on certain platforms, so it's not something Pinta is directly responsible for. If it's directly sampling from what the screen is displaying, and the window manager is dimming the parent window, then that would explain why a different color is being picked

I'd suggest using the color picker tool that's built into Pinta for choosing colours from an image you have open (see attached screenshots). You can then click on a pixel to change Pinta's primary color

<img width="427" alt="Screenshot 2024-03-12 at 10 27 27 PM" src="https://github.com/PintaProject/Pinta/assets/303951/8d8c6fbf-3ef9-4bc0-ab0d-4a7ab9675fec">

<img width="427" alt="Screenshot 2024-03-12 at 10 27 57 PM" src="https://github.com/PintaProject/Pinta/assets/303951/df7b2f76-ad65-4ff1-9ce2-32a9987e6748">
