### ISSUE TITLE
[ Feature ] Quick Color Picker

### ISSUE THREAD

**Issue by PhoneDroid** [PintaProject/Pinta#761]
I'm incredibly happy to have found this project,
I've always missed the in between type of image
editor that Paint.Net provided me on windows ..

<br>

Having said that, the color picker is driving me crazy.

Having to click on a tiny screen region 
![image](https://github.com/PintaProject/Pinta/assets/73050054/76cc0afb-7609-44f9-8e39-f3d6d662188b)

skipping this presets menu
![image](https://github.com/PintaProject/Pinta/assets/73050054/5d060115-5638-41d3-b0df-47df937bc739)

to then not even having an option to use RGB / HSL / HSV inputs
![image](https://github.com/PintaProject/Pinta/assets/73050054/99990554-d790-47a0-8a85-c9eec40a2155)

is quite .. well

<br>

I'd love to see some form of the easy access color picker found in the original paint.net
![image](https://github.com/PintaProject/Pinta/assets/73050054/9462c4d8-613d-4b1f-a636-cb4346936b70)
![image](https://github.com/PintaProject/Pinta/assets/73050054/874b79b4-b9e2-4ab7-bd2c-93dfb2110c9d)

<br>

**Comment by cameronwhite** [comment]
This is pretty similar to bug #570 - this dialog is currently just using the standard system GTK color picker, so isn't any Pinta-specific code, but I agree it's not a great dialog
For entering HSV values, right-clicking on the sliders or the gradient widget will let you enter in specific HSV values

**Comment by evgeniy-harchenko** [comment]
I have some developments in this direction.
![1](https://github.com/PintaProject/Pinta/assets/42656259/e6993411-40b1-4ee8-8053-b09e6bd7e4d8)
But there are a lot of troubles.

First of all I don't understand what is going on with Pinta's versions: why current release has no fixes from master branch? where is gtk4 release version? So I don't know on which branch I should make changes.

Second problem is with palette placing. Now I am using `Overlay`, but it needs correct positioning. We should do correct calculations of the position depending on rulers (are the visible or not) and scrollbars. The second one is the worst problem. The scrollbars are inside widget's content unlike paint.net (winforms), so we should take into account their sizes and visibility in calculations, but unfortunately I haven't found any solutions yet.

**Comment by cameronwhite** [comment]
The `master` branch has been ported to GTK4, which also required porting to a different GTK binding library that supports GTK4. It's been quite a large project so there are many changes compared to the last stable release of 2.1.x

Any new work should absolutely be done on the `master` branch to avoid having to later go through the hassle of porting from GTK3 to GTK4 :) 

For the overlay question, shouldn't the overlay just be relative to the color palette that was clicked on? I'm not clear why it would need to take rulers etc into account

**Comment by cameronwhite** [comment]
The new colour picker dialog is now merged and should improve these issues
