### ISSUE TITLE
Pinta 2.2: Error message on saving file on Windows

### ISSUE THREAD

**Issue by JGCarroll** [PintaProject/Pinta#766]
**Description**
When saving a file on the latest CI build for Windows, on Windows 11 23H2 updated with all the latest public/production updates, using file > save as results in an error message being generated.

The file itself is saved correctly and the error appears harmless.

**To Reproduce**
1) Click File > Save as
2) Save anywhere
3) The error appears

**Additional Info**
![image](https://github.com/PintaProject/Pinta/assets/62413368/a22f0c7f-73cb-49af-9e63-74c623271fab)

**Comment by cameronwhite** [comment]
I wonder if this is something related to Windows 11 - I couldn't reproduce it in my Windows 10 test environment

**Comment by MrCarroll** [comment]
I don't have a copy of Windows 10 to try against, but I did try in a Windows 11 VM (Using the built in Windows Sandbox utility). to try ensure it wasn't system level modifications (not that I have many programs/settings changed from defaults). Some observations would be that this doesn't seem to happen on the first time the Save As window is utilised, but the second time or more time in the same session. It's also not 100% reproducible, but happens with consistency that it should be noticable within a minute (e.g trying 2-5 times should be enough from what I'm seeing).

The error actually also appears before the save button itself is clicked; although usually hidden in the background so it's not noticable until the Save As interface itself is used.

Unfortunately running Pinta.exe in the terminal disconnects STDOUT and there's nothing obvious as to what the error is triggered by.

**Comment by cameronwhite** [comment]
Thanks! Yep, saving a couple times did the trick for me

The stack trace looks very similar to #674 so this might be a similar underlying issue
