### ISSUE TITLE
MacOS Pinta 2.2 beta, Can't build Pinta 2.2 beta

### ISSUE THREAD

**Issue by Mr-Conifer** [PintaProject/Pinta#768]
Can't build Pinta 2.2 beta.

I followed instructions at <>Code tab, ran first two commands. Worked perfectly. However, running the third command caused an error

MSBUILD : error MSB1009: project file doesn't exist.
Key: Pinta

MacOS Sonoma 14.4.1, Pinta 2.2 beta

**Comment by cameronwhite** [comment]
This works for me on macOS - could you let me know the exact command you were running, which folder you were running it form, and your `dotnet --version`?

**Comment by Mr-Conifer** [comment]
dotnet run --project Pinta
dotnet --version 8.0.204

**Comment by cameronwhite** [comment]
Thanks. I was wondering if you were running these commands from the top-level directory of the repository, or some subfolder. Otherwise, I'm not sure why it isn't working for you if the other commands like `dotnet build` did work.

Alternatively, you should be able to just run `dotnet build/bin/Pinta.dll` to launch Pinta rather than `dotnet run ...`

**Comment by Mr-Conifer** [comment]
Still didn't help... Maybe the thing is something to do about the "folder" thing?

**Comment by Mr-Conifer** [comment]
mhlkhrpchnk@MacBook-Air-Mhl ~ % pwd
/Users/mhlkhrpchnk

mhlkhrpchnk@MacBook-Air-Mhl ~ % =ls Pinta.sln
ls: Pinta.sln: No such file or directory

**Comment by Mr-Conifer** [comment]
Am I just a silly guy that doesn't know how to get that .sln file?

**Comment by cameronwhite** [comment]
`Pinta.sln` is in the root folder of the Pinta repository, so you need to do `cd path/to/Pinta` depending on where you cloned the Pinta git repository to on your system. It looks like you are just executing those commands from your home folder

The tutorial steps assume that you are executing the commands from the root folder of the source code

**Comment by Mr-Conifer** [comment]
Thank you! I'm too new at all this "command line" stuff
