### ISSUE TITLE
WebP is not working on macOS builds

### ISSUE THREAD

**Issue by cameronwhite** [PintaProject/Pinta#770]
### Discussed in https://github.com/PintaProject/Pinta/discussions/769

<div type='discussions-op-text'>

<sup>Originally posted by **capellavacancies** April 17, 2024</sup>
I've read online WebP it's supported ([source](https://www.html.it/magazine/pinta-2-1-implementato-il-supporto-a-webp-e-migliorato-quello-per-wayland/)) but when I try to open a WebP file it says it's not supported. Ideas ?</div>

**Comment by badcel** [comment]
It probably is related to this issue?

https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/issues/103

**Comment by cameronwhite** [comment]
Yeah, the `webp-pixbuf-loader` does work to add webP support to Pinta, so it's just matter of packaging it.

I had gotten it packaged properly for macOS, but seem to have not actually merged that in properly

**Comment by cameronwhite** [comment]
This has been backported to the 2.1 branch and will be in the next minor release

**Comment by boltedev** [comment]
This also isn't working in Windows on 2.1.2

**Comment by cameronwhite** [comment]
with b930be3 the webp pixbuf loader is packaged with the Windows installer too. You can try out the latest build from https://github.com/PintaProject/Pinta/actions/runs/9056221969 (requires Github login)
