### ISSUE TITLE
Dark Mode on Windows?

### ISSUE THREAD

**Issue by lunatic-gh** [PintaProject/Pinta#782]
**Description**
IDK if this is a bug, or just a missing feature, but it surely feels like a Bug. On Windows, there's no Dark-Mode whatsoever, no matter what Color is set in Windows Settings.
If there is a Settings menu for pinta, i have yet to find it.

**To Reproduce**
Trying to use the App on Windows (11) i guess?

**Additional Info**
/

**Version**
2.1.2

**Comment by lunatic-gh** [comment]
Actually, after this, i tried thew latest build from the "Actions" page, and that seems to work fine. Even tho it now looks like Linux, and seems to have its own issues, but its better than before.

Thanks for all the work!

**Comment by cameronwhite** [comment]
Yes, the latest builds of Pinta 2.2 use Libadwaita, which should properly switch to a dark theme depending on system settings.
