### ISSUE TITLE
Default zoom changes to 100% when opening multiple files

### ISSUE THREAD

**Issue by dbojan** [PintaProject/Pinta#806]
**Description**
When I open multiple files in Pinta, last opened file is set to fit window, all other files are set to 100% zoom.
I want it to be set, like the last opened file, fit window. If the file is higher resolution than screen I have to unzoom every file.

**To Reproduce**
File/open.
Select multiple files, say 10 files
click open
last file opened is set to fit window zoom
all other 9 files are set to 100% zoom.

**Additional Info**
If applicable, add a screenshot or attach an example file that demonstrates the issue.

**Version**
Please include your operating system (e.g. Ubuntu 22.04) and which version of Pinta (e.g. 2.1) you are using.
windows10, Pinta 2.1.2

**Comment by cameronwhite** [comment]
I can reproduce in Pinta 2.1, but this seems to have already been fixed at some point in Pinta 2.2 development

You can try out the latest development build from https://github.com/PintaProject/Pinta/actions/runs/9072780249
