### ISSUE TITLE
Crash on wayland

### ISSUE THREAD

**Issue by wctrl** [PintaProject/Pinta#809]
**Description**
After about 1 minute app crashes on wayland

**To Reproduce**
This was on hyprland, but it should be applicable for any wayland compositor
1. Run app
2. Do something for ~1 minute
3. Crash

**Additional Info**
stdout log:
```
(pinta:22773): GdkPixbuf-CRITICAL **: 23:18:47.414: gdk_pixbuf_calculate_rowstride: assertion 'width > 0' failed
// ^ it's ok
(pinta:22773): GdkPixbuf-CRITICAL **: 23:18:47.414: gdk_pixbuf_calculate_rowstride: assertion 'width > 0' failed
// ^ it's ok

Gdk-Message: 23:19:12.631: Error 22 (Invalid argument) dispatching to Wayland display.
```
* `// ^ it's ok` means after that app keeps working

**Version**
Arch linux, pinta version - 2.1.2

**Comment by cameronwhite** [comment]
Thanks for the report!

Would you be able to try out the `master` branch to see if it has the same issue?
The master branch is ported to GTK4 (Pinta 2.1 is GTK3) so there's a good chance that might fix Wayland issues in GTK

**Comment by wctrl** [comment]
Yep `master` is fine, closing this
