### ISSUE TITLE
Layers pad does not always update when an update is made

### ISSUE THREAD

**Issue by logiclrd** [PintaProject/Pinta#846]
**Description**
Some actions do not immediately get represented in the miniature preview of the affected layer in the layers pad.

**To Reproduce**
1. Create a new image.
2. Select all pixels. Press Delete.
3. The layer is now entirely translucent, but in the layers pad, it still shows up as opaque white.
4. Select the pencil tool, pick a colour, and draw on the layer. It continues to appear solid white in the layers pad.
5. Add a new layer (e.g. with the first toolbar button beneath the layers pad). Now the preview updates to show what is actually in the background layer.
6. Select the paintbrush tool and draw on layer 2. Its preview does not update.
7. Select the background layer in the layer pad. Now layer 2's preview updates.

**Version**
Operating system: Ubuntu 24.04
Pinta: 2.2 built from 1388aff91ebb35f53717d2a3a7b3ffc9c82b3803

**Comment by cameronwhite** [comment]
It looks like the `HandleHistoryChanged()` method is getting called, so probably the `ItemsChanged()` calls isn't quite correct, or isn't sufficient to actually cause a redraw immediately
