### ISSUE TITLE
Pinta doesn't start after installing on Windows

### ISSUE THREAD

**Issue by Lehonti** [PintaProject/Pinta#859]
I tried downloading and installing the last development build of Pinta on my Windows machine, and I could not get it to run. Also, going to the installation folder and manually running `./Pinta.Exe` does not report any error.

After trying several builds, I noticed that before a certain commit, Pinta runs fine, but after it, it doesn't. Also, the changes introduced by that commit don't seem to be anything that would make the application crash. Also, it runs fine on Ubuntu, so I don't think it's a crash.

I'm using Windows 11. This is how I'd reproduce it:

- Remove installation(s) of Pinta
- Download the zipped Windows installer `Pinta.exe` from the build artifacts, and install it. If it comes from [this](https://github.com/PintaProject/Pinta/commit/97eb3acdd7fe8776efaeb8ce800ba9a489f3d76f) commit (or any commit after this one) it will fail to run; and if it comes from a commit before this one, it will run fine.

**Comment by cameronwhite** [comment]
There was also this bug report on launchpad (https://bugs.launchpad.net/pinta/+bug/2065959) which suggested that the problems started earlier? But maybe something on the CI side was reverted and then reapplied later.

Is there any output if you try launching Pinta.exe from a console? I'm not sure offhand if Windows will show console output for a GUI app, but maybe try `Pinta.exe > output.txt 2>&1`

**Comment by Lehonti** [comment]
Indeed, if I just run `./Pinta.exe` it doesn't show any output.

Running `./Pinta.exe > output.txt 2>&1` creates an empty file `output.txt`.

**Comment by cameronwhite** [comment]
There was a missing dll dependency for the packaged GTK libraries, so this was probably triggered by an MSYS update at some point.
Please give the latest build a test to see if it works for you now. It's working for me on Windows 10 with the latest commit

**Comment by Lehonti** [comment]
Yes @cameronwhite, it runs now. Thanks for taking a look, and opening a related issue :)

**Comment by oubrecht-com** [comment]
Hi, Pinta 3.0.1, 3.0.2 and 3.0.3 has the same problem. Pinta can not start in Windows 11. No error.

**Comment by cameronwhite** [comment]
> Hi, Pinta 3.0.1, 3.0.2 and 3.0.3 has the same problem. Pinta can not start in Windows 11. No error.

I suspect that might be more related to an issue like #1467 - I'd suggest trying out the `GSK_RENDERER` environment variable as mentioned in that bug report to see if that happens to resolve it for you

**Comment by oubrecht-com** [comment]
Yes, it is the same as https://github.com/PintaProject/Pinta/issues/1467 and problem with GSK_RENDER

<img width="1675" height="772" alt="Image" src="https://github.com/user-attachments/assets/f0cc28b3-3667-402e-a12a-78f539b7b930" />
