### ISSUE TITLE
Cannot drag curve in curves window of 2.1.2 (Flatpak)

### ISSUE THREAD

**Issue by arxo** [PintaProject/Pinta#871]
**Description**
In the current Flatpak build of Pinta 2.1.2 altering the curve shape in the Curves adjustment window by dragging it with the mouse is broken.

**To Reproduce**
- install Pinta from Flatpak 
- Open or create image
- Select "Adjustments => Curves..."
- Left-click onto the curve and move mouse to drag. 
=> curve is not bent while dragging, remains fixed

**Additional Info**
![image](https://github.com/PintaProject/Pinta/assets/43294041/d02e1e35-4167-40b0-8830-2a61ce3f8517)

**Version**
Pinta 2.1.2 (Flatpak) on Linux Mint 21.3

**Comment by cameronwhite** [comment]
`Right-click onto the curve and move mouse to drag`
I'm pretty sure it's always been left-click to add a control point and drag, and right-click to remove control points. Did  this work differently before?

**Comment by arxo** [comment]
Right-clicking just removes control points, I cannot drag the curve that way either. I remember it was possible to drag the curve in Pinta. Basically dragging used to work like in Gimp's curves tool.

**Comment by arxo** [comment]
Sorry, I got the mouse buttons mixed up.
It is *left* click to drag, corrected the bug description.

**Comment by cameronwhite** [comment]
Interesting, it works fine on my MacBook, but I was able to reproduce it on a Linux machine.
However, after turning off Num Lock it did work - can you reproduce the same?

I think it might be related to this code which doesn't handle other modifiers being active, and I think Num Lock can cause that to happen sometimes
https://github.com/PintaProject/Pinta/blob/release-2.1/Pinta.Effects/Dialogs/Effects.CurvesDialog.cs#L207

**Comment by arxo** [comment]
Bingo! :) For me it also works with Num Lock off, and fails as soon as I turn it on.
