### ISSUE TITLE
Nightly builds on Flathub beta?

### ISSUE THREAD

**Issue by deusnovus** [PintaProject/Pinta#880]
**Description**

It would be nice to be able to seamlessly install the latest master branch build via Flathub Beta without manually building it, since 2.2 is a massive leap from 2.1.2 and would love to experience Pinta in its GTK4/libadwaita state, even in its current beta state. If it's currently too much work for the team, please don't worry about it!

**Comment by cameronwhite** [comment]
I think that's a great idea, but I'll move this over to the Github repo for the flathub package - I don't really know much about flatpak packaging and how to set up automated builds like that :)

**Comment by cameronwhite** [comment]
Moved to https://github.com/flathub/com.github.PintaProject.Pinta/issues/42
