### ISSUE TITLE
Crashes when tries to add Korean text

### ISSUE THREAD

**Issue by xnuk** [PintaProject/Pinta#903]
**Description**
When I tried to add Korean text (with, like Noto Sans, or whatever), Pinta quits itself

**To Reproduce**
1. Open Pinta
2. Make new file if it doesn't have one
3. Select text tool
4. Click the blank canvas
5. Type Korean
6. Crash

**Additional Info**
stderr: [pinta-korean-crash.gz](https://github.com/user-attachments/files/16071936/pinta-korean-crash.gz)

https://github.com/PintaProject/Pinta/assets/3071003/2bbec332-c894-4921-a6c3-33ab0b85d68e

**Version**
- Pinta 2.1.2
- IME: [Kime](https://github.com/riey/kime) 3.0.2
- Window Manager: [Sway](https://github.com/swaywm/sway) 1.9
- OS: Arch Linux x64 (6.9.7-zen1-1-zen)

**Comment by cameronwhite** [comment]
Thanks for the report! This looks like the same crash as #722 which is fixed in the `master` branch. If you're on Arch Linux you could probably try it out with the `pinta-git` AUR package
