### ISSUE TITLE
Exporting to a flat format should warn you

### ISSUE THREAD

**Issue by Matthieu-LAURENT39** [PintaProject/Pinta#909]
**Description**
Currently, if you're working on a file format that supports layers (like .ora), then decide to export to a flat file format (like .png), all subsequent saves will be done on the PNG file. This is normal, but i keep forgetting about it.  
This lead me to lose all my layers multiple times, as i keep working on the flat file without noticing, and next time i open my ora file, i notice it's out of date, and the png is up to date but without layers. 

I feel like when exporting to a flat format (and you have multiple layers), you should have a prompt warning you that you will lose layer data. 
Also *maybe* merge all the layers with the "flatten" operation after the save? This might be inconvenient, but you'd just be once ctrl+z away from undoing it anyways, and at least it very clearly lets you know that you're losing layer data.

This is also quite important as png is the default format for saving, and first-time users might not realize why none of their layers are being saved.

**Comment by cameronwhite** [comment]
Yeah this would be a good UX improvement.
Probably the `FormatDescriptor` class should be extended to indicate whether the file format is flattened or not , to avoid hardcoding anything for `.ora` files specifically
