### ISSUE TITLE
Pinta empties clipboard on exit

### ISSUE THREAD

**Issue by patrick-7-7-7** [PintaProject/Pinta#911]
Hi there,
is the program meant to empty the clipboard when exiting? 

**To reproduce:**
1. CTRL+C something in Pinta.
2. Test pasting into Skype. Works.
3. ALT+F4 (does not matter if you select "save" or "do not save").
4. Test pasting into Skype. Does not work.

Replacing step 3 with CTRL+W (close the file without closing the program) does not empty the clipboard.

**Version**
2.1.2 (newest) Flatpak com.github.PintaProject.Pinta
Lubuntu (default DE) 24.04

**Comment by patrick-7-7-7** [comment]
I just realized this happened to me with gVim, too. I suppose, you can close this issue.

**Comment by cameronwhite** [comment]
Thanks, yeah I don't think this is anything specific to Pinta's behaviour
