### ISSUE TITLE
Subsequent "save as" file prompts default to the wrong directory

### ISSUE THREAD

**Issue by Matthieu-LAURENT39** [PintaProject/Pinta#914]
**Description**
When opening a "save as" file prompt, it shows the directory that was last used to save an image.
However, if the save fails, a new file prompt opens, and this one seems to use the current working directory rather than the last directory used to save an image.

**To Reproduce**
1. Create an image over 255x255
2. Open the "save as" prompt
3. Save the image as a "ico" file (this is to ensure the save fails as the image is too big)
4. The new prompt defaults to the current working directory, rather than the last used directory.

**Version**
tested on both v2.1.2 and latest master (0755127)

**Comment by cameronwhite** [comment]
This might be platform-specific - on macOS the file picker's directory didn't change for me

**Comment by Matthieu-LAURENT39** [comment]
Personally it happened on linux, specifically under KDE Plasma 6.
Also of note is that i don't have portals enabled, so it's using the GNOME file picker and not the Plasma file picker.
I'll try to dig a little deeper and see what might be causing it.

**Comment by Matthieu-LAURENT39** [comment]
At the very least, moving the `fcd.SetCurrentFolder (dir);` inside the while `fcd.RunBlocking ()` loop fixed the issue on my end.
Should i make a PR with the fix? It's pretty weird that it's platform dependant, so i'm not sure if it could be a GTK bug instead.

**Comment by cameronwhite** [comment]
Pinta does use the native file picker, so there have been various platform-specific problems. I can do some testing on Mac / Windows if you make a PR 👍
