### ISSUE TITLE
atk-bridge

### ISSUE THREAD

**Issue by DetFieldTechs** [PintaProject/Pinta#925]
**Description**
ix@LAB:~$ pinta
libpxbackend-1.0.so: cannot open shared object file: No such file or directory
Failed to load module: /home/russix/snap/pinta/common/.cache/gio-modules/libgiolibproxy.so
Gtk-Message: 20:38:04.071: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.
xkbcommon: ERROR: failed to add default include path /usr/share/X11/xkb
xkbcommon: ERROR: failed to add default include path /usr/share/X11/xkb
Segmentation fault (core dumped)

**To Reproduce**
install mono 12, sudo snap install pinta, then pinta

**Version**
Ubuntu 22.04.4 LTS

**Comment by cameronwhite** [comment]
I think this is the same as this issue which was reported with the snap package earlier today: https://github.com/JGCarroll/pinta-snap/issues/12

**Comment by DetFieldTechs** [comment]
&#x1F386;
