### ISSUE TITLE
Text tool font changes don't take effect unless actively editing

### ISSUE THREAD

**Issue by cameronwhite** [PintaProject/Pinta#952]
This was noted as part of #935 
When there is text that isn't being actively edited (e.g. the user pressed Esc) but hasn't been finalized yet, changes to the font don't redraw immediately and only take effect once a redraw is forced by some other action (e.g. pressing Ctrl, or clicking to start some new text)
These changes should cause a redraw, but https://github.com/PintaProject/Pinta/pull/935#discussion_r1726062748 notes that there may be some other fixes required to achieve this.

https://github.com/user-attachments/assets/5b3c870d-4aa8-48bf-aad2-e02fd7e82033

**Comment by TheodorLasse** [comment]
I'll try to fix this!
