### ISSUE TITLE
Pinta is unable to open files from Finder

### ISSUE THREAD

**Issue by benfll** [PintaProject/Pinta#954]
**Description**
If I try to open an image file with Pinta from Finder, I get the error 

> The document “{filename}” could not be opened. Pinta cannot open files in the “{format}” format.

This happens with any image file, regardless of the format (I tried png, jpg and bmp) and Pinta can open the same files if I use the Open option in its toolbar.

**To Reproduce**
Right-click an image file in Finder, select Open With > Pinta. Pinta opens and error appears.

**Additional Info**
![Screenshot 2024-08-23 at 17 53 21](https://github.com/user-attachments/assets/4e868d0b-310e-4a28-8c74-eeb80e2023ef)

**Version**
I'm running macOS Sonoma 14.6.1. I get this issue on the [latest build](https://github.com/PintaProject/Pinta/actions/runs/10510329065) of Pinta as well as the 2.2 preview build from [here](https://github.com/PintaProject/Pinta/releases/tag/dev-preview-builds), but not release 2.1.2.

**Comment by cameronwhite** [comment]
Just to clarify, this is only happening for you with the 2.2 builds, but 2.1 has worked fine for you?

**Comment by benfll** [comment]
Correct, 2.1.2 works correctly

**Comment by cameronwhite** [comment]
Should be fixed now, thanks for catching this!
