### ISSUE TITLE
Pinta has a very ugly GUI under MONO

### ISSUE THREAD

**Issue by defencedog** [PintaProject/Pinta#977]
**MONO GUI Ugly**
GTK theming under GNOME is required

Using under Armbian Linux

**Comment by cameronwhite** [comment]
Could you provide some more information please? e.g. screenshots of the issue, Pinta version etc

Pinta doesn't use Mono any more, so perhaps an old version of Pinta is being used?

**Comment by defencedog** [comment]
I am using aarch64 on OrangePi3b ...Yes you are correct v1.6.2 ... So I tried to [compile myself](https://github.com/defencedog/orangepi3b_v2.1/tree/main/files_tools/pinta2.2.2_dotnet8) & hurray it worked.

**Comment by cameronwhite** [comment]
Great, thanks for confirming! If you're able to use Snap or Flatpak you also should be able to get a newer Pinta version installed through there

**Comment by defencedog** [comment]
@cameronwhite `snap` take huge resources on SBC
