### ISSUE TITLE
Canvas is not updated when removing layers

### ISSUE THREAD

**Issue by f-i-l-i-p** [PintaProject/Pinta#979]
**Description**
I noticed that there is currently a bug on the master branch that stops the canvas from being updated when a layer is removed.
When the canvas is later updated through some other event, such as drawing something, it updates as expected.

**To Reproduce**
Steps to reproduce the issue.
1. Select the brush and draw something on the base layer
2. Create a new layer
3. Delete the base layer
4. The canvas does not update until something else is drawn to it

**Additional Info**

https://github.com/user-attachments/assets/56c1b22f-41ff-461b-9768-4ac113df2c7a

**Version**
OS: Kubuntu 24.04
Pinta version: 2.2 (The bug does not seem to be present in 2.1.2)

**Comment by cameronwhite** [comment]
Confirmed, undo / redo  of the layer changes also seems to have problems.

I'm not sure if much has changed with that code since Pinta 2.1, but more general changes with the GTK4 port maybe affected how things redraw
I suspect some calls to `Workspace.Invalidate()` might be missing..
