### ISSUE TITLE
[Documentation] Could it be mentioned whether Pinta works with mono, in the main readme or in a FAQ?

### ISSUE THREAD

**Issue by rubyFeedback** [PintaProject/Pinta#982]
[Documentation] Could it be mentioned whether Pinta works with mono, in the main readme or in a FAQ?

I just found the project, but I was not sure if it only works on windows but not on linux.

Could this be made clear on the main readme or elsewhere? That way random folks like me may
instantly know whether this can work on Linux or not. (I assume so, actually, but I was not 100%
certain; and if it works, whether we can compile it from source. I tend to avoid binary packages
if that is possible.)

**Comment by cameronwhite** [comment]
Pinta doesn't use mono anymore, and now uses .NET (which supports Windows, Mac and Linux).
There are instructions in the README for building from source on Linux, if that's what you're looking for?

**Comment by cameronwhite** [comment]
The readme has been updated with links to install Pinta from Flatpak or Snap, as well as mentioning cross-platform support
